ARG DEBIAN_FRONTEND=noninteractive
ARG TZ=Europe/Moscow
ARG PBS_VERSION=latest


FROM debian:trixie-slim AS builder
ARG DEBIAN_FRONTEND
ARG TZ

RUN apt-get -qq update -y && \
    apt-get -qq dist-upgrade -y --no-install-recommends -o Dpkg::Options::="--force-confold" && \
    apt-get -qq install -y --no-install-recommends \
    git curl dpkg-dev ca-certificates jq

ARG PBS_VERSION
RUN if expr "$PBS_VERSION" : '[0-9.-][0-9.-]*' > /dev/null; \
    then export TAG=$(curl -s -H 'Accept: application/vnd.github+json' \
    https://api.github.com/repos/wofferl/proxmox-backup-arm64/tags | jq -r '.[].name' | grep ${PBS_VERSION} | head -n1); \
    else export TAG=$(curl -s -H 'Accept: application/vnd.github+json' \
    https://api.github.com/repos/wofferl/proxmox-backup-arm64/tags | jq -r '.[].name' | head -n1); \
    fi && \
    git clone -b ${TAG} --depth 1 --single-branch https://github.com/wofferl/proxmox-backup-arm64 && \
    cd proxmox-backup-arm64 && \
    ./build.sh download=${TAG}


FROM debian:trixie-slim AS stage
ARG DEBIAN_FRONTEND
ARG TZ

# Install dependencies
RUN apt-get -qq update -y && \
    apt-get -qq dist-upgrade -y --no-install-recommends -o Dpkg::Options::="--force-confold" && \
    apt-get -qq install -y --no-install-recommends \
    less netcat-openbsd iputils-ping iputils-tracepath net-tools \
    curl ca-certificates nano apt-utils dstat ifupdown2 gnupg

# configure repository and install modules
RUN apt -qq modernize-sources -y
RUN sed -i '/Components:/s/main$/main contrib/g' /etc/apt/sources.list.d/debian.sources

RUN apt-get update && \
    apt-get install -y \
    --no-install-recommends \
    zfsutils-linux socat

COPY --from=builder /proxmox-backup-arm64/packages /tmp/packages

RUN cd  /tmp/packages && \
    apt-get install -y --no-install-recommends ./*.deb

RUN echo '' > /etc/apt/sources.list.d/pbs-enterprise.sources

# grab gosu for easy step-down from root
# https://github.com/tianon/gosu/releases
RUN set -eux; \
    apt-get update; \
    apt-get upgrade -y; \
    apt-get install -y gosu; \
    gosu nobody true

#Cleanup
RUN apt-get purge -y --auto-remove -o APT::AutoRemove::RecommendsImportant=false \
    -o APT::AutoRemove::SuggestsImportant=false $BUILD_DEPS && \
    rm -rf /var/lib/apt/lists/* && \
    rm -rf /tmp/*

COPY entrypoint.sh /usr/local/bin/
RUN chmod +x /usr/local/bin/entrypoint.sh


FROM scratch AS release
COPY --from=stage / /

VOLUME /backup
EXPOSE 8007

ENTRYPOINT ["entrypoint.sh"]
CMD [""]
